### ISSUE TITLE
How to validation the model?

### ISSUE THREAD

**Issue by Angel113110** [siqueira-hc/Efficient-Facial-Feature-Learning-with-Wide-Ensemble-based-Convolutional-Neural-Networks#12]
Dear author, I test your model on subset of fer2013. But I have a question. Since you used fer+ label in your work, how can I validation the model? I use origin label of fer2013, it seems not good. Thanks!

**Comment by siqueira-hc** [comment]
Dear Angel113110,

Thank you for contacting me.

The model uploaded to this repository was trained on AffectNet. Therefore, in order to achieve high accuracy on FER2013, you must retrain each convolutional branch as explained in our paper (https://arxiv.org/abs/2001.06338).

The training procedure is not complicated. You can use main_fer_plus.py as a template. Note that you should remove one neuron from the last layer of ESR-9 since FER has one less category than FER+, as explained later.

There are a few concerns regarding FER2013. I suggest reading the FER+ paper (https://arxiv.org/abs/1608.01041) by the Microsoft research group to check the problems with the original labels and the differences between FER2013 and FER2013+. For instance, FER+ added the contempt category to the dataset. Another problem is the noisy labels in FER as illustrated in the following Figure (FER top and FER+ bottom) from FER+'s repository (https://github.com/microsoft/FERPlus).

![image](https://user-images.githubusercontent.com/26622989/79998746-60712500-84bb-11ea-9c34-c65898327cec.png)

Best,
Henrique Siqueira

P.S. I could upload the trained model on FER+ for valuation but the University is currently closed due to COVID-19. Thus, I do not have access to the computer where the model was trained.
