### ISSUE TITLE
How to train a binary task?

### ISSUE THREAD

**Issue by Angel113110** [siqueira-hc/Efficient-Facial-Feature-Learning-with-Wide-Ensemble-based-Convolutional-Neural-Networks#13]
Dear author. Thanks for replying me. I want to use the second way you told to train a binary task. That is only re-train the last layer. How to do with it? I'm new in FER. Can you tell more details?

**Comment by siqueira-hc** [comment]
Dear Angel113110,

Unfortunately, I cannot give you this level of personal support due to time constraints. Nevertheless, the answer to your question is the script main_affectnet_continuous.py.

I recommend checking out blogs that give tutorials of machine learning such as:
https://machinelearningmastery.com/
https://www.pyimagesearch.com/

Once again, thank you for your interest and message.

All the best,
Henrique Siqueira
