### ISSUE TITLE
trainning script？

### ISSUE THREAD

**Issue by ShmilyISCAS** [siqueira-hc/Efficient-Facial-Feature-Learning-with-Wide-Ensemble-based-Convolutional-Neural-Networks#5]
i pretented to use ur method and fine-tunein on other dataset，could u provide ur trainning script？

**Comment by siqueira-hc** [comment]
Dear ShmilyISCAS,

Thank you for your message.

Since you are interested in fine-tuning the model, I will provide to you the training script on FER+ where I fine-tuned ESR-9 (i.e., Ensemble with Shared Representations with nine convolutional branches) originally trained on AffectNet.

When are you planning to start your experiments?
I would have to clean/refactor the code before uploading it to the GitHub, but if you have a coming deadline I can send the current version to your email.

Best,
Henrique Siqueira

**Comment by ShmilyISCAS** [comment]
thx for ur reply,i am now doing my bachelor project,i prepare to start experiment next week,current version is ok,many thanks

**Comment by siqueira-hc** [comment]
Great!
I have sent it to you by email.

Best,
Henrique

p.s. I will close this issue and open a new issue for each training script that is missing.
